name: leotest
description: "A new Flutter project."
publish_to: 'none' # No publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

# Dependencias principales
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.0.5
  http: ^1.1.0       # actualizar a >=1.0.0
  file_picker: ^10.3.3
  mime: ^1.0.3
  http_parser: ^4.0.2
  flutter_dotenv: ^6.0.0
  syncfusion_flutter_pdfviewer: ^31.2.3
  syncfusion_flutter_pdf: ^31.2.3
  pdfx: ^2.4.0
  fl_chart: ^0.70.0




# Dependencias de desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Configuración específica de Flutter
flutter:
  uses-material-design: true

  # Assets: imágenes y otros recursos
  assets:
    - assets/images/
    - .env

  # Ejemplo de fonts personalizadas
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
